services:
  myfarm_api:
    build: .
    image: myfarm_api:dev
    container_name: myfarm_api
    profiles: ["dev"]
    env_file:
      - .env.dev
    environment:
      - PYTHONPATH=/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:rw,delegated
    networks:
      - myfarm_net

networks:
  myfarm_net:
    external: true
